spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1091550215598-37hbqqnm29et9mbm90j4t11nlkl6fuh2.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
            redirect-uri: http://localhost:8080/login/oauth2/code/google
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub